definition:
  openapi: "3.0.0"
  info:
    title: "Elastic Search Express API with Swagger"
    version: "0.1.0"
    description: "This is a Elastic search API application made with Express and documented with Swagger"
    servers:
      - url: baseUrl
        description: "Development Server"
apis: 
  - "./src/swaggerDefs/*.yaml"
